// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB32eLo_f_gv47-hHJXxJZA15-Nta5JKMw',
    appId: '1:885649022280:web:929f7ef642b24c1916e77d',
    messagingSenderId: '885649022280',
    projectId: 'note-app-f5e88',
    authDomain: 'note-app-f5e88.firebaseapp.com',
    databaseURL: 'https://note-app-f5e88-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'note-app-f5e88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh24w5dNYWJgfHxVe-yeJTglz4cd3I0jw',
    appId: '1:885649022280:android:217d93639c0980ec16e77d',
    messagingSenderId: '885649022280',
    projectId: 'note-app-f5e88',
    databaseURL: 'https://note-app-f5e88-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'note-app-f5e88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCitZGIMzNy2qFlbjNNc-Boi177RoQ99Dw',
    appId: '1:885649022280:ios:fee8de81fe6c8ac216e77d',
    messagingSenderId: '885649022280',
    projectId: 'note-app-f5e88',
    databaseURL: 'https://note-app-f5e88-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'note-app-f5e88.appspot.com',
    iosBundleId: 'nemtov.dev.note',
  );
}
